### ISSUE TITLE
Consider dropping support for Ruby 2.1 & 2.2

### ISSUE THREAD

**Issue by dlackty** [line/line-bot-sdk-ruby#102]
Currently, this gem supports Ruby >= 2.1 but the official Ruby support for both 2.1 & 2.2 has ended, and even Ruby 2.3 will be end-of-life soon in March this year.

By raising the minimum supported Ruby version, we can avoid issue like #96, adopt newer version of dependencies (e.g. Rubocop), and use newer Ruby syntax and built-in methods.

**Comment by toduq** [comment]
I think dropping older versions of Ruby makes the following effects.
PROS
- Can use newer syntax and methods in SDK.
- Can use newer dependency libraries in SDK.
CONS
- Developers using older ruby won't be able to upgrade to newer version of this SDK.

Currently, we don't encounter any serious problem to support older Ruby versions,
and we don't have any motivation to drop the support since it doesn't affect maintaining this repository.

We, of course, would welcome your pull-requests for dropping older versions if there are enough reasons (like security issues of dependency libraries of this repository, etc...).
